fail_fast: true

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        exclude: ^server/tests/
        args: [ --strict, --ignore-missing-imports]
